// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'style_data.model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

StyleData _$StyleDataFromJson(Map<String, dynamic> json) => StyleData(
      json['id'] as int?,
      json['factoryId'] as int?,
      json['isNewlyAdded'] as int?,
      json['style'] as String?,
      json['desc1'],
      json['desc2'],
      json['image1'],
      json['image2'],
      json['image3'],
      json['image4'],
      json['customerId'] as int?,
      json['productTypeId'] as int?,
      json['productTypeName'] as String?,
      json['seasonId'],
      json['totOperns'] as int?,
      json['sam'] as int?,
      (json['totalTct'] as num?)?.toDouble(),
      json['isActive'] as bool?,
      json['title'] as String?,
      json['code'] as String?,
      json['brand'],
      json['season'] as String?,
      json['createdBy'] as String?,
      json['createdById'] as int?,
      json['createdDt'] as String?,
      json['updatedBy'] as String?,
      json['updatedDt'] as String?,
      json['styleKhm'] as String?,
      json['styleKhmUpdatedBy'],
      json['styleChi'] as String?,
      json['styleChiUpdatedBy'],
      json['styleVie'] as String?,
      json['styleVieUpdatedBy'],
      json['styleInd'] as String?,
      json['styleIndUpdatedBy'],
      json['styleSpa'] as String?,
      json['styleSpaUpdatedBy'],
      json['linesetup'] == null
          ? null
          : LineSetupData.fromJson(json['linesetup'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$StyleDataToJson(StyleData instance) => <String, dynamic>{
      'id': instance.id,
      'factoryId': instance.factoryId,
      'isNewlyAdded': instance.isNewlyAdded,
      'style': instance.style,
      'desc1': instance.desc1,
      'desc2': instance.desc2,
      'image1': instance.image1,
      'image2': instance.image2,
      'image3': instance.image3,
      'image4': instance.image4,
      'customerId': instance.customerId,
      'productTypeId': instance.productTypeId,
      'productTypeName': instance.productTypeName,
      'seasonId': instance.seasonId,
      'totOperns': instance.totOperns,
      'sam': instance.sam,
      'totalTct': instance.totalTct,
      'isActive': instance.isActive,
      'title': instance.title,
      'code': instance.code,
      'brand': instance.brand,
      'season': instance.season,
      'createdBy': instance.createdBy,
      'createdById': instance.createdById,
      'createdDt': instance.createdDt,
      'updatedBy': instance.updatedBy,
      'updatedDt': instance.updatedDt,
      'styleKhm': instance.styleKhm,
      'styleKhmUpdatedBy': instance.styleKhmUpdatedBy,
      'styleChi': instance.styleChi,
      'styleChiUpdatedBy': instance.styleChiUpdatedBy,
      'styleVie': instance.styleVie,
      'styleVieUpdatedBy': instance.styleVieUpdatedBy,
      'styleInd': instance.styleInd,
      'styleIndUpdatedBy': instance.styleIndUpdatedBy,
      'styleSpa': instance.styleSpa,
      'styleSpaUpdatedBy': instance.styleSpaUpdatedBy,
      'linesetup': instance.linesetup,
    };
