// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'line_shift.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Lineshifts _$LineshiftsFromJson(Map<String, dynamic> json) => Lineshifts(
      json['id'] as int?,
      json['lineId'] as int?,
      json['lineSetupId'] as int?,
      json['startDate'] as String?,
      json['endDate'],
      json['shift'] as String?,
      json['shiftId'] as int?,
      json['workingTime'] as int?,
      json['startTime'] as String?,
      json['endTime'] as String?,
      json['breakTime1'],
      json['durationBreakTime1'] as int?,
      json['breakTime2'],
      json['durationBreakTime2'] as int?,
      json['breakTime3'],
      json['durationBreakTime3'] as int?,
      json['breakTime4'],
      json['durationBreakTime4'] as int?,
      json['breakTime5'],
      json['durationBreakTime5'] as int?,
      json['overTime1'],
      json['durationOverTime1'] as int?,
      json['overTime2'],
      json['durationOverTime2'] as int?,
      json['overTime3'],
      json['durationOverTime3'] as int?,
      json['overTime4'],
      json['durationOverTime4'] as int?,
      json['overTime5'],
      json['durationOverTime5'] as int?,
      json['isActive'] as bool?,
      json['isDelete'] as bool?,
      json['totalOverTime'] as int?,
      json['beforeTotalOverTime'] as int?,
      json['afterTotalOverTime'] as int?,
      json['totalBreakTime'] as int?,
      json['createdBy'] as String?,
      json['createdDt'] as String?,
      json['updatedBy'],
      json['updatedDt'],
      json['actualStartTime'] as String?,
      json['actualEndTime'] as String?,
    );

Map<String, dynamic> _$LineshiftsToJson(Lineshifts instance) =>
    <String, dynamic>{
      'id': instance.id,
      'lineId': instance.lineId,
      'lineSetupId': instance.lineSetupId,
      'startDate': instance.startDate,
      'endDate': instance.endDate,
      'shift': instance.shift,
      'shiftId': instance.shiftId,
      'workingTime': instance.workingTime,
      'startTime': instance.startTime,
      'endTime': instance.endTime,
      'breakTime1': instance.breakTime1,
      'durationBreakTime1': instance.durationBreakTime1,
      'breakTime2': instance.breakTime2,
      'durationBreakTime2': instance.durationBreakTime2,
      'breakTime3': instance.breakTime3,
      'durationBreakTime3': instance.durationBreakTime3,
      'breakTime4': instance.breakTime4,
      'durationBreakTime4': instance.durationBreakTime4,
      'breakTime5': instance.breakTime5,
      'durationBreakTime5': instance.durationBreakTime5,
      'overTime1': instance.overTime1,
      'durationOverTime1': instance.durationOverTime1,
      'overTime2': instance.overTime2,
      'durationOverTime2': instance.durationOverTime2,
      'overTime3': instance.overTime3,
      'durationOverTime3': instance.durationOverTime3,
      'overTime4': instance.overTime4,
      'durationOverTime4': instance.durationOverTime4,
      'overTime5': instance.overTime5,
      'durationOverTime5': instance.durationOverTime5,
      'isActive': instance.isActive,
      'isDelete': instance.isDelete,
      'totalOverTime': instance.totalOverTime,
      'beforeTotalOverTime': instance.beforeTotalOverTime,
      'afterTotalOverTime': instance.afterTotalOverTime,
      'totalBreakTime': instance.totalBreakTime,
      'createdBy': instance.createdBy,
      'createdDt': instance.createdDt,
      'updatedBy': instance.updatedBy,
      'updatedDt': instance.updatedDt,
      'actualStartTime': instance.actualStartTime,
      'actualEndTime': instance.actualEndTime,
    };
