// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'line_viewdata.model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

LineSetupData _$LineSetupDataFromJson(Map<String, dynamic> json) =>
    LineSetupData(
      json['id'] as int?,
      json['styleCode'] as String?,
      json['isNewlyAdded'] as int?,
      json['styleId'] as int?,
      json['line'] as String?,
      json['lineId'] as int?,
      (json['lbr'] as num?)?.toDouble(),
      (json['actualLbr'] as num?)?.toDouble(),
      (json['actualLbrTct'] as num?)?.toDouble(),
      (json['totalWebSmv'] as num?)?.toDouble(),
      (json['totalWebTct'] as num?)?.toDouble(),
      (json['eff'] as num?)?.toDouble(),
      json['effTct'],
      (json['effTgt'] as num?)?.toDouble(),
      (json['effTgtTct'] as num?)?.toDouble(),
      (json['lbrTgt'] as num?)?.toDouble(),
      json['totalOutputTgt'],
      json['orderNo'],
      json['totalManpower'] as int?,
      json['factoryId'] as int?,
      json['customer'] as String?,
      json['customerId'] as int?,
      json['desc1'] as String?,
      json['startDate'] as String?,
      json['completionDate'],
      json['shift'] as String?,
      json['shiftId'] as int?,
      json['uid'] as String?,
      json['startShift'] as String?,
      json['startShiftId'] as int?,
      json['endShift'] as String?,
      json['endShiftId'] as int?,
      json['dailyTarget'] as int?,
      json['quantity'] as int?,
      json['targetEff'] as int?,
      json['desc2'],
      json['lineName'] as String?,
      json['outputTime'],
      json['totalOutput'] as int?,
      json['isActive'] as bool?,
      json['isDelete'] as bool?,
      (json['perf'] as num?)?.toDouble(),
      json['endDate'] as String?,
      json['status'] as int?,
      (json['producedMin'] as num?)?.toDouble(),
      json['producedMinTct'] as int?,
      json['attendedMin'] as int?,
      json['lineNpt'] as int?,
      json['createdBy'] as String?,
      json['createdDt'] as String?,
      json['updatedBy'] as String?,
      json['updatedDt'] as String?,
      json['lineBreaktime'] as int?,
      json['lineOvertime'] as int?,
      json['shiftQuantity'] as int?,
      json['highestEff'],
      json['highestEffTct'],
      json['closedBy'],
      json['lbrGraph'] as String?,
      json['ppaVal'] as String?,
      json['lineStartDate'] as String?,
      json['lineEndDate'] as String?,
      json['styleData'] == null
          ? null
          : StyleData.fromJson(json['styleData'] as Map<String, dynamic>),
      json['mfgLineData'] == null
          ? null
          : LineSetupData.fromJson(json['mfgLineData'] as Map<String, dynamic>),
      json['linenpts'] as List<dynamic>?,
      (json['lineshifts'] as List<dynamic>?)
          ?.map((e) => Lineshifts.fromJson(e as Map<String, dynamic>))
          .toList(),
      json['totalNpt'] as int?,
    );

Map<String, dynamic> _$LineSetupDataToJson(LineSetupData instance) =>
    <String, dynamic>{
      'id': instance.id,
      'styleCode': instance.styleCode,
      'isNewlyAdded': instance.isNewlyAdded,
      'styleId': instance.styleId,
      'line': instance.line,
      'lineId': instance.lineId,
      'lbr': instance.lbr,
      'actualLbr': instance.actualLbr,
      'actualLbrTct': instance.actualLbrTct,
      'totalWebSmv': instance.totalWebSmv,
      'totalWebTct': instance.totalWebTct,
      'eff': instance.eff,
      'effTct': instance.effTct,
      'effTgt': instance.effTgt,
      'effTgtTct': instance.effTgtTct,
      'lbrTgt': instance.lbrTgt,
      'totalOutputTgt': instance.totalOutputTgt,
      'orderNo': instance.orderNo,
      'totalManpower': instance.totalManpower,
      'factoryId': instance.factoryId,
      'customer': instance.customer,
      'customerId': instance.customerId,
      'desc1': instance.desc1,
      'startDate': instance.startDate,
      'completionDate': instance.completionDate,
      'shift': instance.shift,
      'shiftId': instance.shiftId,
      'uid': instance.uid,
      'startShift': instance.startShift,
      'startShiftId': instance.startShiftId,
      'endShift': instance.endShift,
      'endShiftId': instance.endShiftId,
      'dailyTarget': instance.dailyTarget,
      'quantity': instance.quantity,
      'targetEff': instance.targetEff,
      'desc2': instance.desc2,
      'lineName': instance.lineName,
      'outputTime': instance.outputTime,
      'totalOutput': instance.totalOutput,
      'isActive': instance.isActive,
      'isDelete': instance.isDelete,
      'perf': instance.perf,
      'endDate': instance.endDate,
      'status': instance.status,
      'producedMin': instance.producedMin,
      'producedMinTct': instance.producedMinTct,
      'attendedMin': instance.attendedMin,
      'lineNpt': instance.lineNpt,
      'createdBy': instance.createdBy,
      'createdDt': instance.createdDt,
      'updatedBy': instance.updatedBy,
      'updatedDt': instance.updatedDt,
      'lineBreaktime': instance.lineBreaktime,
      'lineOvertime': instance.lineOvertime,
      'shiftQuantity': instance.shiftQuantity,
      'highestEff': instance.highestEff,
      'highestEffTct': instance.highestEffTct,
      'closedBy': instance.closedBy,
      'lbrGraph': instance.lbrGraph,
      'ppaVal': instance.ppaVal,
      'lineStartDate': instance.lineStartDate,
      'lineEndDate': instance.lineEndDate,
      'styleData': instance.styleData,
      'mfgLineData': instance.mfgLineData,
      'linenpts': instance.linenpts,
      'lineshifts': instance.lineshifts,
      'totalNpt': instance.totalNpt,
    };
